### ISSUE TITLE
Little more information, please

### ISSUE THREAD

**Issue by 2braincells2go** [pH-7/Obfuscator-Class#1]
Sorry to bug you with questions but my thick old head is not grasping how to use the class.

I see the usage info but not sinking in.

Would it be too much to ask for real life example of how you obfuscate a PHP script? 

Let's say I have the script below and wish to encode:

`<?php
$t = date("H");
echo "<p>The hour (of the server) is " . $t; 
echo ", and will give the following message:</p>";

if ($t < "10") {
    echo "Have a good morning!";
} elseif ($t < "20") {
    echo "Have a good day!";
} else {
    echo "Have a good night!";
}
?>`

Sure this is very simple and will most likely be embarrassed by not grasping it.

Thank you for your time,

Woody

**Comment by pH-7** [comment]
Hi Woody!

Sorry about that.

Consider the default example https://github.com/pH-7/Obfuscator-Class#usage

```PHP
$sData = <<<'DATA'
$t = date("H");
echo "

The hour (of the server) is " . $t;
echo ", and will give the following message:

";
if ($t < "10") {
echo "Have a good morning!";
} elseif ($t < "20") {
echo "Have a good day!";
} else {
echo "Have a good night!";
}
DATA;

$sObfusationData = new Obfuscator($sData, 'Give a name to the piece of code you want to obfuscate');
file_put_contents('my_obfuscation_data.php', '<?php ' . "\r\n" . $sObfusationData);
```

I tested it locally and works well.

Now run `my_obfuscation_data.php`file  and you will see something like "**The hour (of the server) is 19, and will give the following message: Have a good day!**"

**Comment by 2braincells2go** [comment]
Thank you!

When I tried, mistakenly left off the last DATA below actual script. Knew I would be embarrassed:)

Woody
