### ISSUE TITLE
Can i deobfuscate

### ISSUE THREAD

**Issue by ellix4u** [pH-7/Obfuscator-Class#10]
If i Can i obfuscate/encrypt and delete the original(source) file, how can i deobfuscate/decrypt .
1) Can i deobfuscate/decrypt encrypted file?
2) How can i obfuscate/encrypt multiple files, i use your example 3 in https://github.com/pH-7/Obfuscator-Class

**Comment by pH-7** [comment]
Nothing is impossible but it is not easy. AND this is the goal. Otherwise, why to obfuscate your code if you would have an easy way to deobfuscate it?

Please just keep a copy of the source code you obfuscated as a backup, when you will need to do changes in there for example.
