### ISSUE TITLE
Decode Code Simple

### ISSUE THREAD

**Issue by esjdev** [pH-7/Obfuscator-Class#11]
Simple Decode :D  

Step 1: [https://i.imgur.com/owLjd32.png](https://i.imgur.com/owLjd32.png)
_Script Obfuscated_

Step 2: [https://i.imgur.com/Yjh8VKU.png](https://i.imgur.com/Yjh8VKU.png)
_Copy the contents of the variable $__

Step 3: [https://i.imgur.com/O1WIdjW.png](https://i.imgur.com/O1WIdjW.png)
_Use echo with gzuncompress and base64_decode as shown in the image_

Step 4: [https://i.imgur.com/uyzk0yx.png](https://i.imgur.com/uyzk0yx.png)
_See the result in your browser, as shown in the image._

Step 5: [https://i.imgur.com/59L9xGa.png](https://i.imgur.com/59L9xGa.png)
_Copy the contents of the variable which was shown in the image in "step 4" and use in echo with base_decode as shown in the image in "step 5"_

Result: [https://i.imgur.com/1wy7Zfn.png](https://i.imgur.com/1wy7Zfn.png)

**Comment by abydahana** [comment]
Honestly, the words "this is not a stupid base64 encoding script, but a real and effective obfuscation script" is a sarcasm :)

**Comment by pH-7** [comment]
Probably related to https://github.com/pH-7/Obfuscator-Class/issues/10
