### ISSUE TITLE
Easy deobfuscation

### ISSUE THREAD

**Issue by pixel365** [pH-7/Obfuscator-Class#18]
In the resulting file, you need to find the encoded string (usually # 26).
Then decode it - gzuncompress(base64_decode("str")).
Next, find the encoded string again, and decode it using base64_decode.
Where is the efficiency here?

**Comment by da411d** [comment]
Repo description:
>👨‍💻 Simple and effect

LoL

**Comment by pH-7** [comment]
> In the resulting file, you need to find the encoded string (usually # 26).
> Then decode it - gzuncompress(base64_decode("str")).
> Next, find the encoded string again, and decode it using base64_decode.
> Where is the efficiency here?

The way you explain won't deobfuscation the obfuscated file ([if done with this library](https://github.com/pH-7/Obfuscator-Class))

**Comment by pH-7** [comment]
> Repo description:
> 
> > 👨‍💻 Simple and effective Obfuscator PHP class (this is not a stupid base64 encoding script, but a real and effective obfuscation script)
> 
> LoL

😝 Did you try? I don't think so then 😉 But of course, if doesn't guarantee anything. However, it makes the job much harder than a simple base64 encode 😄

**Comment by pixel365** [comment]
Read carefully and reproduce in person. Obfuscated code is easily deobfuscated. Why did you close?
