### ISSUE TITLE
Issues with <?php tag already included in my original file

### ISSUE THREAD

**Issue by halojoy** [pH-7/Obfuscator-Class#3]
A limitation is that can not be <?php in the beginning of $sData.
Say I load a php file with file_get_contents() which have the php opening tag <?php.
Then it will be an error, if I run Obfuscator.

To cope with this I can do this workaround:
```
$sData = file_get_contents('my.php');
$sData = substr($Data, 5);
```

**Comment by pH-7** [comment]
Hi @halojoy 

I hope I understand your problem.. If you get the contents directly from a PHP file, you can strip `<?php` easily like below to make sure it will work without any issues.

So, change your code to
```php
$sData = file_get_contents('my.php');
$sData = str_replace(array('<?php', '<?'), '', $sData); // Strip PHP open/close tags
```

**Comment by pH-7** [comment]
@halojoy Hi again! 😃 

I updated README for giving you an even clearer example

https://github.com/pH-7/Obfuscator-Class#example-3


Ref: https://github.com/pH-7/Obfuscator-Class/commit/ac1c28d4691d2b8db8b90179a430000f42e66db8

**Comment by pH-7** [comment]
I will close it for now. If you have another problem, please reopen the ticket.

**Comment by pH-7** [comment]
FYI, I tested my example and works well 👍
