### ISSUE TITLE
A fix for the <?php thing

### ISSUE THREAD

**Issue by halojoy** [pH-7/Obfuscator-Class#4]
Unfortunately removing open and close tags will not work. 
As you show in example.
I have tested on a script and it does not good.

I am using this fix in your Obfuscator class.
```
    public function __construct($sData, $sName)
    {
        $this->sName = $sName;
        $this->sData = $sData;
        if (substr($this->sData, 0, 5) == '<?php') {
            $this->sData = substr($this->sData, 5);
        }
```

**Comment by pH-7** [comment]
Hi again @halojoy 
Please remove the PHP open/close tags before calling the class like I show you (my example works).
https://github.com/pH-7/Obfuscator-Class#example-3

Happy New Year's Eve

Good luck!

**Comment by pH-7** [comment]
Hi again @halojoy 
Please remove the PHP open/close tags before calling Obfuscator class like I show you (my example works).
```php
$sData = str_replace(array('<?php', '<?', '?>'), '', $sData); // Strip PHP open/close tags
$sObfusationData = new Obfuscator($sData, 'My Class'); // Now, I instance the class!
```
https://github.com/pH-7/Obfuscator-Class#example-3

Happy New Year's Eve

Good luck!

**Comment by pH-7** [comment]
And don't forget to **Star** the repo 😺

**Comment by pH-7** [comment]
And don't forget to **Star** the repo 😺  @halojoy
