### ISSUE TITLE
Replace create_function() to anonymous function 

### ISSUE THREAD

**Issue by pH-7** [pH-7/Obfuscator-Class#6]
[create_function()](https://secure.php.net/manual/en/function.create-function.php) is deprecated since PHP 7.2.
Obfuscator class currently uses `create_function()` [here](https://github.com/pH-7/Obfuscator-Class/blob/master/src/Obfuscator.php#L61). It will have to be replaced by [anonymous function](https://www.php.net/manual/en/functions.anonymous.php) + update the the [unit tests](https://github.com/pH-7/Obfuscator-Class/tree/master/tests).

**Comment by halojoy** [comment]
Great. Thank you.

**Comment by oleteacher** [comment]
Do not wish to bother you, but any idea if/when you may find time to fix this issue?

Thanks in advance,

Susan

**Comment by oleteacher** [comment]
So sad that the project died. We are using in our school classroom for projects and cannot find a good simple solution like yours...

**Comment by pH-7** [comment]
Hey @oleteacher :)

This library isn't dead! It still works well and does well the job 🙂
`create_function` is just depreciated at the moment, because PHP has now closures. That's all.

For the moment, you can just turn off the depreciated warnings from PHP with `E_DEPRECATED` https://www.php.net/manual/en/function.error-reporting.php

At the moment, the library works better (I mean, obfuscates/hides better) with `create_function`

I will probably have to rewrite a bunch of code in there in order to get rid of `create_function`

**Comment by oleteacher** [comment]
"For the moment, you can just turn off the depreciated warnings from PHP with E_DEPRECATED"

Thanks for info. Unfortunatly that method is forbidden on the school network. But will try at home.

**Comment by pH-7** [comment]
👍

**Comment by juliocesar757** [comment]
It would be great to update the code. It is the best free obfuscator for PHP.

**Comment by federicobouzas** [comment]
I'm looking forward to get fixed this issue too!! Thanks

**Comment by alexey-shishkin** [comment]
Hello! 

Any updates about this issue? Will it be resolved? Thanks in advance.

**Comment by overherz** [comment]
Please make this update

**Comment by Amigamerlin** [comment]
Please make the update to have it working with php 7.3.x / 7.4.x.
Thank you !!!

**Comment by pH-7** [comment]
Hey @halojoy, @oleteacher, @juliocesar757 and @Amigamerlin 
The script is now compatible with PHP 7.2 and beyond! 🚀 Better late than never :) Hope you will appreciate the hard work!

**Comment by pH-7** [comment]
> Hello!
> 
> Any updates about this issue? Will it be resolved? Thanks in advance.

This is now thing done! https://github.com/pH-7/Obfuscator-Class/pull/14 
Hope it will be useful to you!

**Comment by pH-7** [comment]
Just released the new version: https://github.com/pH-7/Obfuscator-Class/releases/tag/v2.0.0 Tested and works as expected.

**Comment by Mwangangi** [comment]
@pH-7  Thank you for this new release! Works like charm!!

**Comment by juliocesar757** [comment]
Wow! This is amazing! Thank you so much!

**Comment by oleteacher** [comment]
You just made my day, thank you!

**Comment by overherz** [comment]
Fatal error: Cannot redeclare __lambda() (previously declared ....

**Comment by pH-7** [comment]
> Fatal error: Cannot redeclare __lambda() (previously declared ....

Thanks! Now fixed. https://github.com/pH-7/Obfuscator-Class/commit/92a59d73b2578995f868574950701ee026383872

**Comment by pH-7** [comment]
> Wow! This is amazing! Thank you so much!

You're very welcome @juliocesar757, @oleteacher! Please feel free to open an issue if you find any bugs. Today, I released [the v2.0.1](https://github.com/pH-7/Obfuscator-Class/releases/tag/v2.0.1) fixing the bug @overherz mentioned.

**Comment by pH-7** [comment]
> @pH-7 Thank you for this new release! Works like charm!!

So happy for you! 🤗
By the way, FYI, I released the v2.0.1 today fixing a bug which was causing a PHP fatal error when several obfuscated files were included at once. This might not be the case, but it if could be, don't forget to update the script :)

**Comment by pH-7** [comment]
> @pH-7 Thank you for this new release! Works like charm!!

So happy for you @Mwangangi! 🤗
By the way, FYI, I released the v2.0.1 today fixing a bug which was causing a PHP fatal error when several obfuscated files were included at once. This might not be the case, but it if could be, don't forget to update the script :)
