### ISSUE TITLE
Licenses in LICENSE.txt and composer.json do not match? 

### ISSUE THREAD

**Issue by AndreasRydberg** [pH-7/Obfuscator-Class#7]
LICENSE.txt says Creative Commons and composer.json says GPL-3.0-or-later. Which is the correct one?

**Comment by pH-7** [comment]
Good catch. Used to be under Creative Attribution 3.0 license several years ago. I will fix it in the next upcoming version.

**Comment by pH-7** [comment]
It will actually be distributed under MIT license 🎉
