### ISSUE TITLE
Parse error problem & fix

### ISSUE THREAD

**Issue by arcencielltd** [pH-7/Obfuscator-Class#9]
Although the supplied examples worked fine, when I tried with my own code I got: 
"Parse error: syntax error, unexpected '<', expecting end of file"
I contacted Pierre-Henry and he very kindly gave me the solution which is to omit the opening and closing "<?php" and "?>" tags around the code.

**Comment by Ellatifh** [comment]
I've get the same error "Parse error: syntax error, unexpected '<', expecting end of file" and i didnt get your solution , may you clarify please ?

**Comment by arcencielltd** [comment]
The examples I saw were bracketed by double-quote signs so I put those into my code. In fact, those are not valid.  Make sure your code starts with a less-than sign and ends with a semi-colon.

**Comment by pH-7** [comment]
Looks like you included also the PHP open tag ‘<?php’

Please make sure to omit it before to obfuscate the code. Thanks!
